language: elixir
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 19.2
    - elixir: 1.6.1
      otp_release: 20.2

after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
