language: elixir
elixir:
    - 1.4.5
opt_release:
    - 20.0
matrix:
  include:
    - elixir: 1.4.4
      otp_release: 19.2

after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
